name: spark_templates
version: 0.0.1
author: Alexander Ewetumo<trinoxf@gmail.com>
description: providing client-side dom components for sparkflow
homepage: http://github.com/influx6/spark-elements.dart
dependencies:
  hub: any
  sparkflow: any
